import { CodebasePayload } from "./types";

export const dummyPayload: CodebasePayload = {
    repositoryName: "DemoCodebase",
    totalFilesAnalyzed: 8,
    nodes: [
        {
            id: "src/index.ts",
            path: "src/index.ts",
            name: "index.ts",
            type: "file",
            language: "typescript",
            summary: "Main application entry point. Initializes server and connects to database.",
            cyclomatic_complexity: 5,
            centrality_score: 0.9,
            is_core_node: true,
            coordinates: { x: 0, y: 0, z: 0 },
        },
        {
            id: "src/auth.ts",
            path: "src/auth.ts",
            name: "auth.ts",
            type: "file",
            language: "typescript",
            summary: "Handles user authentication, JWT verification, and OAuth flows.",
            cyclomatic_complexity: 12,
            centrality_score: 0.8,
            is_core_node: true,
            coordinates: { x: 60, y: 40, z: 20 },
        },
        {
            id: "src/utils/helpers.ts",
            path: "src/utils/helpers.ts",
            name: "helpers.ts",
            type: "file",
            language: "typescript",
            summary: "Common utility functions for string manipulation and date parsing.",
            cyclomatic_complexity: 3,
            centrality_score: 0.3,
            is_core_node: false,
            coordinates: { x: -50, y: -60, z: -10 },
        },
        {
            id: "src/components/Button.tsx",
            path: "src/components/Button.tsx",
            name: "Button.tsx",
            type: "file",
            language: "tsx",
            summary: "Reusable UI Button component with variants.",
            cyclomatic_complexity: 2,
            centrality_score: 0.4,
            is_core_node: false,
            coordinates: { x: 120, y: -30, z: 50 },
        },
        {
            id: "src/components/Layout.tsx",
            path: "src/components/Layout.tsx",
            name: "Layout.tsx",
            type: "file",
            language: "tsx",
            summary: "Main page layout wrapper with sidebar and header.",
            cyclomatic_complexity: 4,
            centrality_score: 0.7,
            is_core_node: false,
            coordinates: { x: 80, y: -80, z: 40 },
        },
        {
            id: "src/api/users.ts",
            path: "src/api/users.ts",
            name: "users.ts",
            type: "file",
            language: "typescript",
            summary: "API endpoints for user CRUD operations.",
            cyclomatic_complexity: 8,
            centrality_score: 0.75,
            is_core_node: true,
            coordinates: { x: -80, y: 50, z: -30 },
        },
        {
            id: "src/api/posts.ts",
            path: "src/api/posts.ts",
            name: "posts.ts",
            type: "file",
            language: "typescript",
            summary: "API endpoints for creating and fetching posts.",
            cyclomatic_complexity: 6,
            centrality_score: 0.65,
            is_core_node: false,
            coordinates: { x: -100, y: 20, z: -20 },
        },
        {
            id: "src/db/connection.ts",
            path: "src/db/connection.ts",
            name: "connection.ts",
            type: "file",
            language: "typescript",
            summary: "Database connection setup and schema synchronization.",
            cyclomatic_complexity: 4,
            centrality_score: 0.85,
            is_core_node: true,
            coordinates: { x: -30, y: 100, z: -50 },
        },
    ],
    edges: [
        { source: "src/index.ts", target: "src/auth.ts", weight: 3 },
        { source: "src/index.ts", target: "src/db/connection.ts", weight: 4 },
        { source: "src/index.ts", target: "src/api/users.ts", weight: 2 },
        { source: "src/index.ts", target: "src/api/posts.ts", weight: 2 },
        { source: "src/auth.ts", target: "src/utils/helpers.ts", weight: 1 },
        { source: "src/api/users.ts", target: "src/db/connection.ts", weight: 5 },
        { source: "src/api/posts.ts", target: "src/db/connection.ts", weight: 4 },
        { source: "src/components/Layout.tsx", target: "src/auth.ts", weight: 2 },
        { source: "src/components/Layout.tsx", target: "src/components/Button.tsx", weight: 1 },
    ],
};
